/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Aluno;
import dao.AlunoDAO;

/**
 *
 * @author Alunos
 */
public class EditarAluno extends javax.swing.JFrame {

 private Aluno aluno;

 public void setAluno(Aluno aluno) {
  this.aluno = aluno;
  jTextFieldId.setText(String.valueOf(aluno.getId()));
  jTextFieldNome.setText(aluno.getNome());
  jTextFieldNota1.setText(String
          .valueOf(aluno.getNota1()));
  jTextFieldNota2.setText(String
          .valueOf(aluno.getNota2()));
  jTextFieldNota3.setText(String
          .valueOf(aluno.getNota3()));
  jTextFieldNota4.setText(String
          .valueOf(aluno.getNota4()));
  jTextFieldQuantidadeFaltas.setText(String
          .valueOf(aluno.getQuantidadeFaltas()));
 }

 /**
  * Creates new form AlunoCadastro
  */
 public EditarAluno() {
  initComponents();
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jLabel1 = new javax.swing.JLabel();
  jTextFieldNome = new javax.swing.JTextField();
  jLabel2 = new javax.swing.JLabel();
  jTextFieldQuantidadeFaltas = new javax.swing.JTextField();
  jLabel3 = new javax.swing.JLabel();
  jTextFieldNota1 = new javax.swing.JTextField();
  jLabel4 = new javax.swing.JLabel();
  jTextFieldNota2 = new javax.swing.JTextField();
  jLabel5 = new javax.swing.JLabel();
  jTextFieldNota3 = new javax.swing.JTextField();
  jLabel6 = new javax.swing.JLabel();
  jTextFieldNota4 = new javax.swing.JTextField();
  jButtonEditar = new javax.swing.JButton();
  jLabel7 = new javax.swing.JLabel();
  jTextFieldId = new javax.swing.JTextField();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

  jLabel1.setText("Nome");

  jLabel2.setText("Quantidade de Faltas");

  jLabel3.setText("Nota 1");

  jLabel4.setText("Nota 2");

  jLabel5.setText("Nota 3");

  jLabel6.setText("Nota 4");

  jButtonEditar.setText("Editar");
  jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButtonEditarActionPerformed(evt);
   }
  });

  jLabel7.setText("Id");

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addComponent(jLabel7)
     .addGroup(layout.createSequentialGroup()
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
       .addComponent(jTextFieldId, javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jTextFieldQuantidadeFaltas, javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jTextFieldNota1, javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jTextFieldNota2, javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jTextFieldNota3, javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
       .addComponent(jTextFieldNota4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
      .addGap(18, 18, 18)
      .addComponent(jButtonEditar)))
    .addContainerGap(39, Short.MAX_VALUE))
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(jLabel7)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jLabel1)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jLabel2)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jTextFieldQuantidadeFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jLabel3)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jTextFieldNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jLabel4)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jTextFieldNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jLabel5)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(jTextFieldNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(jLabel6)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(jTextFieldNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(jButtonEditar))
    .addGap(24, 24, 24))
  );

  pack();
 }// </editor-fold>//GEN-END:initComponents

 private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

  Aluno aluno = new Aluno();
  aluno.setNome(jTextFieldNome.getText());
  aluno.setNota1(Double.parseDouble(
          jTextFieldNota1.getText()));
  aluno.setNota2(Double.parseDouble(
          jTextFieldNota2.getText()));
  aluno.setNota3(Double.parseDouble(
          jTextFieldNota3.getText()));
  aluno.setNota4(Double.parseDouble(
          jTextFieldNota4.getText()));
  aluno.setQuantidadeFaltas(Integer.parseInt(
          jTextFieldQuantidadeFaltas.getText()));
  aluno.setId(Integer.parseInt(
          jTextFieldId.getText()));
  boolean alterado = new AlunoDAO().alterar(aluno);


 }//GEN-LAST:event_jButtonEditarActionPerformed

 /**
  * @param args the command line arguments
  */
 public static void main(String args[]) {
  /* Set the Nimbus look and feel */
  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
  try {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(EditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex) {
   java.util.logging.Logger.getLogger(EditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex) {
   java.util.logging.Logger.getLogger(EditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
   java.util.logging.Logger.getLogger(EditarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
  //</editor-fold>
  //</editor-fold>
  //</editor-fold>
  //</editor-fold>

  /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run() {
    new EditarAluno().setVisible(true);
   }
  });
 }

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JButton jButtonEditar;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JLabel jLabel4;
 private javax.swing.JLabel jLabel5;
 private javax.swing.JLabel jLabel6;
 private javax.swing.JLabel jLabel7;
 private javax.swing.JTextField jTextFieldId;
 private javax.swing.JTextField jTextFieldNome;
 private javax.swing.JTextField jTextFieldNota1;
 private javax.swing.JTextField jTextFieldNota2;
 private javax.swing.JTextField jTextFieldNota3;
 private javax.swing.JTextField jTextFieldNota4;
 private javax.swing.JTextField jTextFieldQuantidadeFaltas;
 // End of variables declaration//GEN-END:variables
}
